#!/bin/sh -e

scons platform=x11 \
		target=release_debug \
		execinfo=yes \
		pulseaudio=no \
		use_lto=yes \
		production=yes \
		deprecated=no \
		bits=64

install -Dm755 bin/godot.x11.opt.tools.64 "$1/usr/bin/godot"
